# Generated by Django 3.2.3 on 2021-07-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('asset', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Snagg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('asset', models.CharField(default='unit', max_length=100)),
                ('createdTime', models.DateTimeField(blank='True', null='True')),
                ('createdBy', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=25)),
                ('action', models.CharField(max_length=255)),
                ('closedTime', models.DateTimeField(blank='True', null='True')),
                ('image_file', models.FileField(blank='True', null='True', upload_to='')),
            ],
        ),
    ]
