# Generated by Django 3.2.5 on 2021-07-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snagg',
            new_name='WorkOrder',
        ),
    ]
