# Generated by Django 3.2.3 on 2021-07-21 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0002_rename_snagg_workorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='WoEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editedBy', models.CharField(max_length=100)),
                ('editedTime', models.DateTimeField()),
                ('wonumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorder.workorder')),
            ],
        ),
    ]
