# Generated by Django 3.2.3 on 2021-07-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0003_woevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='woevents',
            name='event',
            field=models.CharField(default='', max_length=250),
        ),
    ]
